# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://bugoslinux.github.io/
title: BugOS | Linux Distro
email: dropall@email.com
author: HenryJr
description: > # "Write an awesome description for your new site here. 
  BugOS Linux é sem dúvida a distribuição mais popular no mundo inteiro.
copyright: 'Copyright &copy; 2020 Henry Jr. All Rights Reserved.'
credits: 'Credits: Henry Jr, Adão Duque, Presto, Marcelo Baptista, Henry, Gilgamesh e Reginaldo.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/bugoslinux
  - title: github
    url: https://github.com/bugoslinux
  - title: telegram
    url: https://telegram.me/joinchat/CYyDAT0Jg_EVAEedD9qgsw
